version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: api-test
    ports:
      - "8001:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api:/app
      - dev-static-data:/api/static
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme

volumes:
  db-data:
  dev-static-data: